apiVersion: v1
kind: Namespace
metadata:
  name: appns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: appns
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: f4rsh4d/connectionstatus:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: api_key
              value: ppppp==
            - name: delay
              value: "30"
            - name: elk_url
              value: https://url:9200
            - name: host
              value: sh-local-kube
            - name: index_name
              value: indexname
            - name: pipeline
              value: DateChanger
          volumeMounts:
            - mountPath: /apt/config.py
              subPath: config.py
              name: application-configmap
      volumes:
        - name: application-configmap
          configMap:
            name: appconfig

